name: Build OP64D7L1 SukiSU Ultra GKI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y git curl make gcc bc bison flex libssl-dev python3

      - name: Clone GKI kernel 6.12
        run: |
          git clone --depth=1 https://android.googlesource.com/kernel/common -b android16-6.12 kernel
          cd kernel

      - name: Add SukiSU Ultra
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s builtin

      - name: Add SUSFS
        run: |
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android16-6.12
          cd kernel
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android16-6.12.patch ./
          patch -p1 < 50_add_susfs_in_gki-android16-6.12.patch

      - name: Build GKI
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make gki_defconfig
          make -j$(nproc)

      - name: Make AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3
          cp kernel/arch/arm64/boot/Image AnyKernel3/
          cd AnyKernel3
          zip -r9 OP64D7L1_SukiSU_GKI.zip *

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: OP64D7L1_SukiSU_Ultra_GKI
          path: AnyKernel3/OP64D7L1_SukiSU_GKI.zip
